### ISSUE TITLE
GPS 

### ISSUE THREAD

**Issue by zackgreen** [sciguy14/Arduino-Tutorial-Series#3]
i'm going to do project base on gps and ardunio. project name call online tracking system and its a web base. i just want to know how to plot on google maps live gps data and how to display in my web. Thanks :)

**Comment by johntal** [comment]
What about using ubidots or a service like that? Or try http://www.instructables.com/id/Real-Time-GPS-Tracker-with-Integrated-Google-Maps/?ALLSTEPS

If you get it working please let me know and upload the code. 

Thanks
John

**Comment by zackgreen** [comment]
thank you bro ill check .
